### ISSUE TITLE
Detailing, Fixing, Refactoring

### ISSUE THREAD

**Issue by MiljkovicVeljko** [KrisZivojevic/My-portfolio#13]
- [x] Border disappearing bug
- [x] Store CV in G-Drive, and replace href link in Resume button
- [x] Hover underline (or similar) on nav links
- [x] Change favicon and title in head
- [x] Add id to each section and link it with navigation buttons

1. Button in the header section looks like losing the border on the hover, change its color to fix this small issue.
2. Remove CV from the application, and store it in your own G-drive, share with anyone and replace a link in Navigation Button. Double-check if you need download attribute anymore and how its works.

**Comment by MiljkovicVeljko** [comment]
- [ ] clear errors in console 

1. Warning: Invalid DOM property `fill-opacity`. Did you mean `fillOpacity`?

**Comment by KrisZivojevic** [comment]
Warning resolved.
