### ISSUE TITLE
Project section

### ISSUE THREAD

**Issue by KrisZivojevic** [KrisZivojevic/My-portfolio#2]
- [ ]  Card component
![image](https://user-images.githubusercontent.com/101418000/209574081-71a2f3cd-129c-4501-b6d7-94a83063256c.png)

- [ ]  Add GitHub link & Live demo
- [ ]  App screenshot for cards

**Comment by MiljkovicVeljko** [comment]
- [x] Project component
- [x] use react-icons with links to demo and github
- [x] Project component needs to have bold h3, below needs to be description in p tag, and at the bottom of the project component needs to be tech stack included in project
- [x] Show more bottom without functionality
![image](https://user-images.githubusercontent.com/47921421/209931460-7298db3b-e6c3-490c-9e91-3876186e3c96.png)
