### ISSUE TITLE
Contact section

### ISSUE THREAD

**Issue by KrisZivojevic** [KrisZivojevic/My-portfolio#5]
- [ ] Form
- [ ] Form logic (send to email)
![image](https://user-images.githubusercontent.com/101418000/209575027-93ad5a3d-4602-4cbf-9006-29ac5e31432e.png)
![image](https://user-images.githubusercontent.com/101418000/209575059-3899d251-41bf-436f-a3d2-fd2451340909.png)

**Comment by MiljkovicVeljko** [comment]
We do not need form yet, we can go with this.

- [x] contact component needs to have (top-to-bottom) span, h2, p and button 
- [x] for button use shared component across whole project
- [x] button need to be link with mailto option. e.g. mailto:kristinazivojevic@gmail.com

example:

![image](https://user-images.githubusercontent.com/47921421/209931916-7cd8b5b9-b90d-46a0-9881-38739467cbdb.png)
