### ISSUE TITLE
Testimonials section

### ISSUE THREAD

**Issue by KrisZivojevic** [KrisZivojevic/My-portfolio#7]
- [ ] Slider
![image](https://user-images.githubusercontent.com/101418000/209575265-2c224438-dd67-4e65-9c79-aaa361fd7fff.png)

**Comment by MiljkovicVeljko** [comment]
Delete previous comment

- [ ] title and subtitle are static part
- [ ] red area is switchable, that needs to be component (testimonial) and to accept img, qoute, name, position in props


![image](https://user-images.githubusercontent.com/47921421/209935376-b70d7835-c098-41aa-964f-04a97ca455a0.png)
