### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by KrisZivojevic** [KrisZivojevic/My-portfolio#8]
- [x] Add social networks icons and links
- [x] Copyright
- [x] Add content

**Comment by MiljkovicVeljko** [comment]
- [ ] install React-icons for social networks icons

Quick guide to icons in react:
Tip: use FaFacebook, FaInstagram and FaLinkedin 
![image](https://user-images.githubusercontent.com/47921421/209887257-383f0276-6548-4902-8020-e213aeffd686.png)
![image](https://user-images.githubusercontent.com/47921421/209887302-fbd051ea-1ae7-47f2-b494-155d65a3c72b.png)
![image](https://user-images.githubusercontent.com/47921421/209887540-96923fbe-2be0-4d4e-8d9a-c0902e0a1d80.png)

Footer need to be similar as this:

![image](https://user-images.githubusercontent.com/47921421/209887078-bdd491cd-dfb8-4186-a06e-ec11fcebf46d.png)
