### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by KrisZivojevic** [KrisZivojevic/My-portfolio#9]
- [ ] Scroll to top
- [ ] Dark mode

**Comment by MiljkovicVeljko** [comment]
1. Add React-Icon dark/light in navigation
2. Add Scroll to top library
https://www.makeuseof.com/how-to-add-dark-mode-to-a-react-application/

https://www.npmjs.com/package/react-scroll-to-top

- [x] install library: `npm i react-scroll-to-top`
- [x] in App.js import component from it : _import ScrollToTop from "react-scroll-to-top";_
- [x] in App.js call component above the navigation: _<ScrollToTop smooth style={{ backgroundColor: colors.teal }} height="20" width='20' color={colors.mint} />_
- [x] add teal color to constants.js: _teal: "#154042"_

**Comment by MiljkovicVeljko** [comment]
Arrows scroll down animation

- [x] In Header folder create new folder Arrows
- [x] In Arrows folder create two files Arrows.js and Arrows.module.css
- [x] In Arrows.js return attached svg 
- [x] In Arrows.module.css paste styles bellow
- [x] In Header.module.css add position: relative; in .header__styled class

`<svg className={styles.arrows}>
      <path className={styles.a1} d="M0 0 L30 32 L60 0"></path>
      <path className={styles.a2} d="M0 20 L30 52 L60 20"></path>
      <path className={styles.a3} d="M0 40 L30 72 L60 40"></path>
    </svg>`

`.arrows {
  position: absolute;
  left: 50%;
  width: 60px;
	height: 72px;
	margin-left: -30px;
	bottom: 100px;
}
.arrows path {
  stroke: var(--teal);
	fill: transparent;
	stroke-width: 1px;	
	animation: arrow 2s infinite;
	-webkit-animation: arrow 2s infinite; 
}

@keyframes arrow
{
0% {opacity:0}
40% {opacity:1}
80% {opacity:0}
100% {opacity:0}
}

@-webkit-keyframes arrow /*Safari and Chrome*/
{
0% {opacity:0}
40% {opacity:1}
80% {opacity:0}
100% {opacity:0}
}
.arrows path.a1 {
  animation-delay:-1s;
	-webkit-animation-delay:-1s; /* Safari 和 Chrome */
}
.arrows path.a2 {
	animation-delay:-0.5s;
	-webkit-animation-delay:-0.5s; /* Safari 和 Chrome */
}
.arrows path.a3 {
	animation-delay:0s;
	-webkit-animation-delay:0s; /* Safari 和 Chrome */
}

@media screen and (max-width: 678px) {
  .arrows {
    bottom: 30px;
  }
}`
